/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface AnonymousHousingQualityAssessmentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "assessments"
      | "assessors"
      | "certifyAssessor"
      | "getAssessmentInfo"
      | "getAssessorStats"
      | "getPropertyAssessmentCount"
      | "getPropertyAssessmentIds"
      | "getQualityReport"
      | "getTotalAssessments"
      | "nextAssessmentId"
      | "owner"
      | "propertyAssessments"
      | "protocolId"
      | "qualityReports"
      | "registerAssessor"
      | "submitQualityAssessment"
      | "verifyAssessment"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssessmentSubmitted"
      | "AssessmentVerified"
      | "AssessorCertified"
      | "AssessorRegistered"
      | "QualityReportGenerated"
      | "SafetyIssueDetected"
      | "StructuralIssueDetected"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "assessments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "assessors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "certifyAssessor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAssessmentInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAssessorStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPropertyAssessmentCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPropertyAssessmentIds",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getQualityReport",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalAssessments",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextAssessmentId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "propertyAssessments",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "qualityReports",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAssessor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitQualityAssessment",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAssessment",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "assessments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "assessors", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "certifyAssessor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssessmentInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssessorStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPropertyAssessmentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPropertyAssessmentIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQualityReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalAssessments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextAssessmentId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "propertyAssessments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "qualityReports",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAssessor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitQualityAssessment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAssessment",
    data: BytesLike
  ): Result;
}

export namespace AssessmentSubmittedEvent {
  export type InputTuple = [
    assessmentId: BigNumberish,
    assessor: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    assessmentId: bigint,
    assessor: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    assessmentId: bigint;
    assessor: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssessmentVerifiedEvent {
  export type InputTuple = [assessmentId: BigNumberish, verifier: AddressLike];
  export type OutputTuple = [assessmentId: bigint, verifier: string];
  export interface OutputObject {
    assessmentId: bigint;
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssessorCertifiedEvent {
  export type InputTuple = [assessor: AddressLike, certifier: AddressLike];
  export type OutputTuple = [assessor: string, certifier: string];
  export interface OutputObject {
    assessor: string;
    certifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssessorRegisteredEvent {
  export type InputTuple = [assessor: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [assessor: string, timestamp: bigint];
  export interface OutputObject {
    assessor: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QualityReportGeneratedEvent {
  export type InputTuple = [
    assessmentId: BigNumberish,
    publicScore: BigNumberish
  ];
  export type OutputTuple = [assessmentId: bigint, publicScore: bigint];
  export interface OutputObject {
    assessmentId: bigint;
    publicScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SafetyIssueDetectedEvent {
  export type InputTuple = [assessmentId: BigNumberish, propertyId: string];
  export type OutputTuple = [assessmentId: bigint, propertyId: string];
  export interface OutputObject {
    assessmentId: bigint;
    propertyId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StructuralIssueDetectedEvent {
  export type InputTuple = [assessmentId: BigNumberish, propertyId: string];
  export type OutputTuple = [assessmentId: bigint, propertyId: string];
  export interface OutputObject {
    assessmentId: bigint;
    propertyId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AnonymousHousingQualityAssessment extends BaseContract {
  connect(runner?: ContractRunner | null): AnonymousHousingQualityAssessment;
  waitForDeployment(): Promise<this>;

  interface: AnonymousHousingQualityAssessmentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  assessments: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        boolean,
        boolean,
        string
      ] & {
        encryptedStructuralScore: string;
        encryptedSafetyScore: string;
        encryptedUtilityScore: string;
        encryptedLocationScore: string;
        encryptedOverallScore: string;
        assessor: string;
        timestamp: bigint;
        isVerified: boolean;
        isCompleted: boolean;
        encryptedPropertyId: string;
      }
    ],
    "view"
  >;

  assessors: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, boolean, bigint, bigint, bigint] & {
        isRegistered: boolean;
        isCertified: boolean;
        totalAssessments: bigint;
        verifiedAssessments: bigint;
        registrationTime: bigint;
      }
    ],
    "view"
  >;

  certifyAssessor: TypedContractMethod<
    [assessor: AddressLike],
    [void],
    "nonpayable"
  >;

  getAssessmentInfo: TypedContractMethod<
    [assessmentId: BigNumberish],
    [
      [string, bigint, boolean, boolean, string] & {
        assessor: string;
        timestamp: bigint;
        isVerified: boolean;
        isCompleted: boolean;
        encryptedPropertyId: string;
      }
    ],
    "view"
  >;

  getAssessorStats: TypedContractMethod<
    [assessor: AddressLike],
    [
      [boolean, boolean, bigint, bigint, bigint] & {
        isRegistered: boolean;
        isCertified: boolean;
        totalAssessments: bigint;
        verifiedAssessments: bigint;
        registrationTime: bigint;
      }
    ],
    "view"
  >;

  getPropertyAssessmentCount: TypedContractMethod<
    [encryptedPropertyId: string],
    [bigint],
    "view"
  >;

  getPropertyAssessmentIds: TypedContractMethod<
    [encryptedPropertyId: string],
    [bigint[]],
    "view"
  >;

  getQualityReport: TypedContractMethod<
    [assessmentId: BigNumberish],
    [
      [bigint, boolean, boolean, boolean, bigint] & {
        publicOverallScore: bigint;
        hasStructuralIssues: boolean;
        hasSafetyIssues: boolean;
        hasUtilityIssues: boolean;
        reportTime: bigint;
      }
    ],
    "view"
  >;

  getTotalAssessments: TypedContractMethod<[], [bigint], "view">;

  nextAssessmentId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  propertyAssessments: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  qualityReports: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, boolean, boolean, boolean, bigint] & {
        assessmentId: bigint;
        publicOverallScore: bigint;
        hasStructuralIssues: boolean;
        hasSafetyIssues: boolean;
        hasUtilityIssues: boolean;
        reportTime: bigint;
      }
    ],
    "view"
  >;

  registerAssessor: TypedContractMethod<[], [void], "nonpayable">;

  submitQualityAssessment: TypedContractMethod<
    [
      _structuralScore: BigNumberish,
      _safetyScore: BigNumberish,
      _utilityScore: BigNumberish,
      _locationScore: BigNumberish,
      _encryptedPropertyId: string
    ],
    [void],
    "nonpayable"
  >;

  verifyAssessment: TypedContractMethod<
    [assessmentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "assessments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        boolean,
        boolean,
        string
      ] & {
        encryptedStructuralScore: string;
        encryptedSafetyScore: string;
        encryptedUtilityScore: string;
        encryptedLocationScore: string;
        encryptedOverallScore: string;
        assessor: string;
        timestamp: bigint;
        isVerified: boolean;
        isCompleted: boolean;
        encryptedPropertyId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "assessors"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, boolean, bigint, bigint, bigint] & {
        isRegistered: boolean;
        isCertified: boolean;
        totalAssessments: bigint;
        verifiedAssessments: bigint;
        registrationTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "certifyAssessor"
  ): TypedContractMethod<[assessor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAssessmentInfo"
  ): TypedContractMethod<
    [assessmentId: BigNumberish],
    [
      [string, bigint, boolean, boolean, string] & {
        assessor: string;
        timestamp: bigint;
        isVerified: boolean;
        isCompleted: boolean;
        encryptedPropertyId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAssessorStats"
  ): TypedContractMethod<
    [assessor: AddressLike],
    [
      [boolean, boolean, bigint, bigint, bigint] & {
        isRegistered: boolean;
        isCertified: boolean;
        totalAssessments: bigint;
        verifiedAssessments: bigint;
        registrationTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPropertyAssessmentCount"
  ): TypedContractMethod<[encryptedPropertyId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPropertyAssessmentIds"
  ): TypedContractMethod<[encryptedPropertyId: string], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getQualityReport"
  ): TypedContractMethod<
    [assessmentId: BigNumberish],
    [
      [bigint, boolean, boolean, boolean, bigint] & {
        publicOverallScore: bigint;
        hasStructuralIssues: boolean;
        hasSafetyIssues: boolean;
        hasUtilityIssues: boolean;
        reportTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalAssessments"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextAssessmentId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "propertyAssessments"
  ): TypedContractMethod<[arg0: string, arg1: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "qualityReports"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, boolean, boolean, boolean, bigint] & {
        assessmentId: bigint;
        publicOverallScore: bigint;
        hasStructuralIssues: boolean;
        hasSafetyIssues: boolean;
        hasUtilityIssues: boolean;
        reportTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerAssessor"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitQualityAssessment"
  ): TypedContractMethod<
    [
      _structuralScore: BigNumberish,
      _safetyScore: BigNumberish,
      _utilityScore: BigNumberish,
      _locationScore: BigNumberish,
      _encryptedPropertyId: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyAssessment"
  ): TypedContractMethod<[assessmentId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "AssessmentSubmitted"
  ): TypedContractEvent<
    AssessmentSubmittedEvent.InputTuple,
    AssessmentSubmittedEvent.OutputTuple,
    AssessmentSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "AssessmentVerified"
  ): TypedContractEvent<
    AssessmentVerifiedEvent.InputTuple,
    AssessmentVerifiedEvent.OutputTuple,
    AssessmentVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "AssessorCertified"
  ): TypedContractEvent<
    AssessorCertifiedEvent.InputTuple,
    AssessorCertifiedEvent.OutputTuple,
    AssessorCertifiedEvent.OutputObject
  >;
  getEvent(
    key: "AssessorRegistered"
  ): TypedContractEvent<
    AssessorRegisteredEvent.InputTuple,
    AssessorRegisteredEvent.OutputTuple,
    AssessorRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "QualityReportGenerated"
  ): TypedContractEvent<
    QualityReportGeneratedEvent.InputTuple,
    QualityReportGeneratedEvent.OutputTuple,
    QualityReportGeneratedEvent.OutputObject
  >;
  getEvent(
    key: "SafetyIssueDetected"
  ): TypedContractEvent<
    SafetyIssueDetectedEvent.InputTuple,
    SafetyIssueDetectedEvent.OutputTuple,
    SafetyIssueDetectedEvent.OutputObject
  >;
  getEvent(
    key: "StructuralIssueDetected"
  ): TypedContractEvent<
    StructuralIssueDetectedEvent.InputTuple,
    StructuralIssueDetectedEvent.OutputTuple,
    StructuralIssueDetectedEvent.OutputObject
  >;

  filters: {
    "AssessmentSubmitted(uint32,address,uint256)": TypedContractEvent<
      AssessmentSubmittedEvent.InputTuple,
      AssessmentSubmittedEvent.OutputTuple,
      AssessmentSubmittedEvent.OutputObject
    >;
    AssessmentSubmitted: TypedContractEvent<
      AssessmentSubmittedEvent.InputTuple,
      AssessmentSubmittedEvent.OutputTuple,
      AssessmentSubmittedEvent.OutputObject
    >;

    "AssessmentVerified(uint32,address)": TypedContractEvent<
      AssessmentVerifiedEvent.InputTuple,
      AssessmentVerifiedEvent.OutputTuple,
      AssessmentVerifiedEvent.OutputObject
    >;
    AssessmentVerified: TypedContractEvent<
      AssessmentVerifiedEvent.InputTuple,
      AssessmentVerifiedEvent.OutputTuple,
      AssessmentVerifiedEvent.OutputObject
    >;

    "AssessorCertified(address,address)": TypedContractEvent<
      AssessorCertifiedEvent.InputTuple,
      AssessorCertifiedEvent.OutputTuple,
      AssessorCertifiedEvent.OutputObject
    >;
    AssessorCertified: TypedContractEvent<
      AssessorCertifiedEvent.InputTuple,
      AssessorCertifiedEvent.OutputTuple,
      AssessorCertifiedEvent.OutputObject
    >;

    "AssessorRegistered(address,uint256)": TypedContractEvent<
      AssessorRegisteredEvent.InputTuple,
      AssessorRegisteredEvent.OutputTuple,
      AssessorRegisteredEvent.OutputObject
    >;
    AssessorRegistered: TypedContractEvent<
      AssessorRegisteredEvent.InputTuple,
      AssessorRegisteredEvent.OutputTuple,
      AssessorRegisteredEvent.OutputObject
    >;

    "QualityReportGenerated(uint32,uint32)": TypedContractEvent<
      QualityReportGeneratedEvent.InputTuple,
      QualityReportGeneratedEvent.OutputTuple,
      QualityReportGeneratedEvent.OutputObject
    >;
    QualityReportGenerated: TypedContractEvent<
      QualityReportGeneratedEvent.InputTuple,
      QualityReportGeneratedEvent.OutputTuple,
      QualityReportGeneratedEvent.OutputObject
    >;

    "SafetyIssueDetected(uint32,string)": TypedContractEvent<
      SafetyIssueDetectedEvent.InputTuple,
      SafetyIssueDetectedEvent.OutputTuple,
      SafetyIssueDetectedEvent.OutputObject
    >;
    SafetyIssueDetected: TypedContractEvent<
      SafetyIssueDetectedEvent.InputTuple,
      SafetyIssueDetectedEvent.OutputTuple,
      SafetyIssueDetectedEvent.OutputObject
    >;

    "StructuralIssueDetected(uint32,string)": TypedContractEvent<
      StructuralIssueDetectedEvent.InputTuple,
      StructuralIssueDetectedEvent.OutputTuple,
      StructuralIssueDetectedEvent.OutputObject
    >;
    StructuralIssueDetected: TypedContractEvent<
      StructuralIssueDetectedEvent.InputTuple,
      StructuralIssueDetectedEvent.OutputTuple,
      StructuralIssueDetectedEvent.OutputObject
    >;
  };
}
