/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AnonymousHousingQualityAssessment } from "./AnonymousHousingQualityAssessment";
export type { IFHEVMGateway } from "./IFHEVMGateway";
